#ifndef __OCARINA_GENERATED_ACTIVITY_H_
#define __OCARINA_GENERATED_ACTIVITY_H_ 
#include <request.h>
/*****************************************************/

/*  This file was automatically generated by Ocarina */

/*  Do NOT hand-modify this file, as your            */

/*  changes will be lost when you re-run Ocarina     */

/*****************************************************/

void the_thread_motion_deliver 
    (__po_hi_request_t* request);

void* the_thread_motion_job (void);

void the_thread_control_deliver 
    (__po_hi_request_t* request);

void* the_thread_control_job (void);

void the_thread_awake_deliver 
    (__po_hi_request_t* request);

void* the_thread_awake_job (void);

void the_thread_awake_rules_deliver 
    (__po_hi_request_t* request);

void* the_thread_awake_rules_job (void);

void the_thread_video_deliver 
    (__po_hi_request_t* request);

void* the_thread_video_job (void);

void the_thread_car_deliver 
    (__po_hi_request_t* request);

void* the_thread_car_job (void);

void __po_hi_main_deliver 
    (__po_hi_request_t* request);

#endif
