#include <po_hi_gqueue.h>
#include <deployment.h>
#include <po_hi_types.h>
#include <request.h>
#include <types.h>
#include "subprograms.h"
#include <activity.h>
#include <po_hi_task.h>
#include <po_hi_main.h>
#include <po_hi_transport.h>
/*****************************************************/
/*  This file was automatically generated by Ocarina */
/*  Do NOT hand-modify this file, as your            */
/*  changes will be lost when you re-run Ocarina     */
/*****************************************************/
__po_hi_port_t __po_hi_the_thread_motion_motion_out_local_destinations[1] = {the_thread_control_global_motion_in};
__po_hi_uint8_t __po_hi_the_thread_motion_woffsets[__po_hi_the_thread_motion_nb_ports];
__po_hi_uint8_t __po_hi_the_thread_motion_offsets[__po_hi_the_thread_motion_nb_ports];
__po_hi_uint8_t __po_hi_the_thread_motion_used_size[__po_hi_the_thread_motion_nb_ports];
__po_hi_uint8_t __po_hi_the_thread_motion_empties[__po_hi_the_thread_motion_nb_ports];
__po_hi_uint8_t __po_hi_the_thread_motion_first[__po_hi_the_thread_motion_nb_ports];
__po_hi_request_t __po_hi_the_thread_motion_recent[__po_hi_the_thread_motion_nb_ports];
__po_hi_port_t __po_hi_the_thread_motion_queue[0 * sizeof (__po_hi_request_t)];
__po_hi_uint16_t __po_hi_the_thread_motion_total_fifo_size = 0;
__po_hi_local_port_t __po_hi_the_thread_motion_history[0];
__po_hi_uint8_t __po_hi_the_thread_motion_n_dest[__po_hi_the_thread_motion_nb_ports] = {0,1};
__po_hi_int8_t __po_hi_the_thread_motion_fifo_size[__po_hi_the_thread_motion_nb_ports] = {__PO_HI_GQUEUE_FIFO_INDATA,__PO_HI_GQUEUE_FIFO_OUT};
__po_hi_port_t* __po_hi_the_thread_motion_destinations[__po_hi_the_thread_motion_nb_ports] = {NULL,__po_hi_the_thread_motion_motion_out_local_destinations};

/*!
 * \fn void the_thread_motion_deliver (__po_hi_request_t* request)
 * \brief Function that delivers requests to the task the_thread_motion
 *
 * When the generated application received a request, it calls a main delivery
 *  function that redirects to localfunctions for each task. This function 
 * (the_thread_motion_deliver) stores the incoming request for the 
 * taskthe_thread_motion
 */
void the_thread_motion_deliver 
    (__po_hi_request_t* request)
{

  switch (request->port)
  {
    case the_thread_motion_global_motion_in:
    {
      __po_hi_gqueue_store_in (the_controller_the_thread_motion_k, the_thread_motion_local_motion_in, request);

      break;
    }
    default:
    {
      break;
    }
  }
}


/*!
 * \fn void* the_thread_motion_job (void)
 * \brief Function executed by the task the_thread_motion
 *
 * This function is executed as soon as the task  is created. It performs the 
 * following operations:  Receive incoming data,  Execute tasks subprograms,  
 * Send output data.
 */
/*  Periodic task : the_thread_motion*/
/*  Get the IN ports values*/
void* the_thread_motion_job (void)
{
  __po_hi_request_t static motion_in_request;
  home_types__state person_in_room_request_var;
  __po_hi_request_t motion_out_request;
  __po_hi_int32_t error;

  __po_hi_gqueue_init (the_controller_the_thread_motion_k, __po_hi_the_thread_motion_nb_ports, __po_hi_the_thread_motion_queue, __po_hi_the_thread_motion_fifo_size, __po_hi_the_thread_motion_first, __po_hi_the_thread_motion_offsets, __po_hi_the_thread_motion_woffsets, __po_hi_the_thread_motion_n_dest, __po_hi_the_thread_motion_destinations, __po_hi_the_thread_motion_used_size, __po_hi_the_thread_motion_history, __po_hi_the_thread_motion_recent, __po_hi_the_thread_motion_empties, __po_hi_the_thread_motion_total_fifo_size);
  
/*!
 * Waiting for other tasks initialization
 */
  __po_hi_wait_initialization ();
  __po_hi_compute_next_period (the_controller_the_thread_motion_k);
  
/*!
 * Waiting for the first dispatch instant
 */
  __po_hi_wait_for_next_period (the_controller_the_thread_motion_k);
  
/*!
 * Task body
 */
  while (1)
  {
    /* :: Yes if commentary :: */if (__po_hi_gqueue_get_count (the_controller_the_thread_motion_k, the_thread_motion_local_motion_in))
    {
          __po_hi_gqueue_get_value (the_controller_the_thread_motion_k, the_thread_motion_local_motion_in, &(motion_in_request));
      __po_hi_gqueue_next_value (the_controller_the_thread_motion_k, the_thread_motion_local_motion_in);

    }
    /*  Call implementation*/
    syst__motion_processing (motion_in_request.vars.the_thread_motion_global_motion_in.the_thread_motion_global_motion_in, &(person_in_room_request_var));
    /*  Set the OUT port values*/
    motion_out_request.vars.the_thread_motion_global_motion_out.the_thread_motion_global_motion_out = motion_out_request_var;
    motion_out_request.port = the_thread_motion_global_motion_out;
    __po_hi_gqueue_store_out (the_controller_the_thread_motion_k, the_thread_motion_local_motion_out, &(motion_out_request));
    /*  Send the OUT ports*/
    error =
     __po_hi_send_output (the_controller_the_thread_motion_k, the_thread_motion_global_motion_out);
    __po_hi_wait_for_next_period (the_controller_the_thread_motion_k);
  }
}

__po_hi_port_t __po_hi_the_thread_control_camera_out_local_destinations[1] = {the_camera_global_camera_on_off};
__po_hi_port_t __po_hi_the_thread_control_light_out_local_destinations[1] = {the_light_global_light_on_off};
__po_hi_port_t __po_hi_the_thread_control_heat_out_local_destinations[1] = {the_heater_global_heater_on_off};
__po_hi_port_t __po_hi_the_thread_control_music_out_local_destinations[1] = {the_music_global_music_on_off};
__po_hi_port_t __po_hi_the_thread_control_alarm_out_local_destinations[1] = {the_alarm_unit_global_alarm_on_off};
__po_hi_port_t __po_hi_the_thread_control_gate_out_local_destinations[1] = {the_garage_gate_global_garage_on_off};
__po_hi_uint8_t __po_hi_the_thread_control_woffsets[__po_hi_the_thread_control_nb_ports];
__po_hi_uint8_t __po_hi_the_thread_control_offsets[__po_hi_the_thread_control_nb_ports];
__po_hi_uint8_t __po_hi_the_thread_control_used_size[__po_hi_the_thread_control_nb_ports];
__po_hi_uint8_t __po_hi_the_thread_control_empties[__po_hi_the_thread_control_nb_ports];
__po_hi_uint8_t __po_hi_the_thread_control_first[__po_hi_the_thread_control_nb_ports];
__po_hi_request_t __po_hi_the_thread_control_recent[__po_hi_the_thread_control_nb_ports];
__po_hi_port_t __po_hi_the_thread_control_queue[0 * sizeof (__po_hi_request_t)];
__po_hi_uint16_t __po_hi_the_thread_control_total_fifo_size = 0;
__po_hi_local_port_t __po_hi_the_thread_control_history[0];
__po_hi_uint8_t __po_hi_the_thread_control_n_dest[__po_hi_the_thread_control_nb_ports] = {0,0,1,1,1,1,1,0,1};
__po_hi_int8_t __po_hi_the_thread_control_fifo_size[__po_hi_the_thread_control_nb_ports] = {__PO_HI_GQUEUE_FIFO_INDATA,__PO_HI_GQUEUE_FIFO_INDATA,__PO_HI_GQUEUE_FIFO_OUT,__PO_HI_GQUEUE_FIFO_OUT,__PO_HI_GQUEUE_FIFO_OUT,__PO_HI_GQUEUE_FIFO_OUT,__PO_HI_GQUEUE_FIFO_OUT,__PO_HI_GQUEUE_FIFO_INDATA,__PO_HI_GQUEUE_FIFO_OUT};
__po_hi_port_t* __po_hi_the_thread_control_destinations[__po_hi_the_thread_control_nb_ports] = {NULL,NULL,__po_hi_the_thread_control_camera_out_local_destinations,__po_hi_the_thread_control_light_out_local_destinations,__po_hi_the_thread_control_heat_out_local_destinations,__po_hi_the_thread_control_music_out_local_destinations,__po_hi_the_thread_control_alarm_out_local_destinations,NULL,__po_hi_the_thread_control_gate_out_local_destinations};

/*!
 * \fn void the_thread_control_deliver (__po_hi_request_t* request)
 * \brief Function that delivers requests to the task the_thread_control
 *
 * When the generated application received a request, it calls a main delivery
 *  function that redirects to localfunctions for each task. This function 
 * (the_thread_control_deliver) stores the incoming request for the 
 * taskthe_thread_control
 */
void the_thread_control_deliver 
    (__po_hi_request_t* request)
{

  switch (request->port)
  {
    case the_thread_control_global_video_not_recognized:
    {
      __po_hi_gqueue_store_in (the_controller_the_thread_control_k, the_thread_control_local_video_not_recognized, request);

      break;
    }
    case the_thread_control_global_motion_in:
    {
      __po_hi_gqueue_store_in (the_controller_the_thread_control_k, the_thread_control_local_motion_in, request);

      break;
    }
    case the_thread_control_global_gate_in:
    {
      __po_hi_gqueue_store_in (the_controller_the_thread_control_k, the_thread_control_local_gate_in, request);

      break;
    }
    default:
    {
      break;
    }
  }
}


/*!
 * \fn void* the_thread_control_job (void)
 * \brief Function executed by the task the_thread_control
 *
 * This function is executed as soon as the task  is created. It performs the 
 * following operations:  Receive incoming data,  Execute tasks subprograms,  
 * Send output data.
 */
/*  Periodic task : the_thread_control*/
/*  Get the IN ports values*/
void* the_thread_control_job (void)
{
  __po_hi_request_t static video_not_recognized_request;
  __po_hi_request_t static motion_in_request;
  __po_hi_request_t static gate_in_request;
  home_types__state camera_out_request_var;
  home_types__state light_out_request_var;
  home_types__state heat_out_request_var;
  home_types__state music_out_request_var;
  home_types__state alarm_out_request_var;
  home_types__state gate_out_request_var;
  __po_hi_request_t camera_out_request;
  __po_hi_request_t light_out_request;
  __po_hi_request_t heat_out_request;
  __po_hi_request_t music_out_request;
  __po_hi_request_t alarm_out_request;
  __po_hi_request_t gate_out_request;
  __po_hi_int32_t error;

  __po_hi_gqueue_init (the_controller_the_thread_control_k, __po_hi_the_thread_control_nb_ports, __po_hi_the_thread_control_queue, __po_hi_the_thread_control_fifo_size, __po_hi_the_thread_control_first, __po_hi_the_thread_control_offsets, __po_hi_the_thread_control_woffsets, __po_hi_the_thread_control_n_dest, __po_hi_the_thread_control_destinations, __po_hi_the_thread_control_used_size, __po_hi_the_thread_control_history, __po_hi_the_thread_control_recent, __po_hi_the_thread_control_empties, __po_hi_the_thread_control_total_fifo_size);
  
/*!
 * Waiting for other tasks initialization
 */
  __po_hi_wait_initialization ();
  __po_hi_compute_next_period (the_controller_the_thread_control_k);
  
/*!
 * Waiting for the first dispatch instant
 */
  __po_hi_wait_for_next_period (the_controller_the_thread_control_k);
  
/*!
 * Task body
 */
  while (1)
  {
    /* :: Yes if commentary :: */if (__po_hi_gqueue_get_count (the_controller_the_thread_control_k, the_thread_control_local_video_not_recognized))
    {
          __po_hi_gqueue_get_value (the_controller_the_thread_control_k, the_thread_control_local_video_not_recognized, &(video_not_recognized_request));
      __po_hi_gqueue_next_value (the_controller_the_thread_control_k, the_thread_control_local_video_not_recognized);

    }
    /* :: Yes if commentary :: */if (__po_hi_gqueue_get_count (the_controller_the_thread_control_k, the_thread_control_local_motion_in))
    {
          __po_hi_gqueue_get_value (the_controller_the_thread_control_k, the_thread_control_local_motion_in, &(motion_in_request));
      __po_hi_gqueue_next_value (the_controller_the_thread_control_k, the_thread_control_local_motion_in);

    }
    /* :: Yes if commentary :: */if (__po_hi_gqueue_get_count (the_controller_the_thread_control_k, the_thread_control_local_gate_in))
    {
          __po_hi_gqueue_get_value (the_controller_the_thread_control_k, the_thread_control_local_gate_in, &(gate_in_request));
      __po_hi_gqueue_next_value (the_controller_the_thread_control_k, the_thread_control_local_gate_in);

    }
    /*  Call implementation*/
    syst__control_processing (motion_in_request.vars.the_thread_control_global_motion_in.the_thread_control_global_motion_in, video_not_recognized_request.vars.the_thread_control_global_video_not_recognized.the_thread_control_global_video_not_recognized, &(camera_out_request_var), &(light_out_request_var), &(heat_out_request_var), &(music_out_request_var), &(alarm_out_request_var), gate_in_request.vars.the_thread_control_global_gate_in.the_thread_control_global_gate_in, &(gate_out_request_var));
    /*  Set the OUT port values*/
    camera_out_request.vars.the_thread_control_global_camera_out.the_thread_control_global_camera_out = camera_out_request_var;
    camera_out_request.port = the_thread_control_global_camera_out;
    __po_hi_gqueue_store_out (the_controller_the_thread_control_k, the_thread_control_local_camera_out, &(camera_out_request));
    light_out_request.vars.the_thread_control_global_light_out.the_thread_control_global_light_out = light_out_request_var;
    light_out_request.port = the_thread_control_global_light_out;
    __po_hi_gqueue_store_out (the_controller_the_thread_control_k, the_thread_control_local_light_out, &(light_out_request));
    heat_out_request.vars.the_thread_control_global_heat_out.the_thread_control_global_heat_out = heat_out_request_var;
    heat_out_request.port = the_thread_control_global_heat_out;
    __po_hi_gqueue_store_out (the_controller_the_thread_control_k, the_thread_control_local_heat_out, &(heat_out_request));
    music_out_request.vars.the_thread_control_global_music_out.the_thread_control_global_music_out = music_out_request_var;
    music_out_request.port = the_thread_control_global_music_out;
    __po_hi_gqueue_store_out (the_controller_the_thread_control_k, the_thread_control_local_music_out, &(music_out_request));
    alarm_out_request.vars.the_thread_control_global_alarm_out.the_thread_control_global_alarm_out = alarm_out_request_var;
    alarm_out_request.port = the_thread_control_global_alarm_out;
    __po_hi_gqueue_store_out (the_controller_the_thread_control_k, the_thread_control_local_alarm_out, &(alarm_out_request));
    gate_out_request.vars.the_thread_control_global_gate_out.the_thread_control_global_gate_out = gate_out_request_var;
    gate_out_request.port = the_thread_control_global_gate_out;
    __po_hi_gqueue_store_out (the_controller_the_thread_control_k, the_thread_control_local_gate_out, &(gate_out_request));
    /*  Send the OUT ports*/
    error =
     __po_hi_send_output (the_controller_the_thread_control_k, the_thread_control_global_camera_out);
    error =
     __po_hi_send_output (the_controller_the_thread_control_k, the_thread_control_global_light_out);
    error =
     __po_hi_send_output (the_controller_the_thread_control_k, the_thread_control_global_heat_out);
    error =
     __po_hi_send_output (the_controller_the_thread_control_k, the_thread_control_global_music_out);
    error =
     __po_hi_send_output (the_controller_the_thread_control_k, the_thread_control_global_alarm_out);
    error =
     __po_hi_send_output (the_controller_the_thread_control_k, the_thread_control_global_gate_out);
    __po_hi_wait_for_next_period (the_controller_the_thread_control_k);
  }
}

__po_hi_port_t __po_hi_the_thread_awake_motion_out_local_destinations[1] = {the_thread_awake_rules_global_motion_in};
__po_hi_uint8_t __po_hi_the_thread_awake_woffsets[__po_hi_the_thread_awake_nb_ports];
__po_hi_uint8_t __po_hi_the_thread_awake_offsets[__po_hi_the_thread_awake_nb_ports];
__po_hi_uint8_t __po_hi_the_thread_awake_used_size[__po_hi_the_thread_awake_nb_ports];
__po_hi_uint8_t __po_hi_the_thread_awake_empties[__po_hi_the_thread_awake_nb_ports];
__po_hi_uint8_t __po_hi_the_thread_awake_first[__po_hi_the_thread_awake_nb_ports];
__po_hi_request_t __po_hi_the_thread_awake_recent[__po_hi_the_thread_awake_nb_ports];
__po_hi_port_t __po_hi_the_thread_awake_queue[0 * sizeof (__po_hi_request_t)];
__po_hi_uint16_t __po_hi_the_thread_awake_total_fifo_size = 0;
__po_hi_local_port_t __po_hi_the_thread_awake_history[0];
__po_hi_uint8_t __po_hi_the_thread_awake_n_dest[__po_hi_the_thread_awake_nb_ports] = {0,1};
__po_hi_int8_t __po_hi_the_thread_awake_fifo_size[__po_hi_the_thread_awake_nb_ports] = {__PO_HI_GQUEUE_FIFO_INDATA,__PO_HI_GQUEUE_FIFO_OUT};
__po_hi_port_t* __po_hi_the_thread_awake_destinations[__po_hi_the_thread_awake_nb_ports] = {NULL,__po_hi_the_thread_awake_motion_out_local_destinations};

/*!
 * \fn void the_thread_awake_deliver (__po_hi_request_t* request)
 * \brief Function that delivers requests to the task the_thread_awake
 *
 * When the generated application received a request, it calls a main delivery
 *  function that redirects to localfunctions for each task. This function 
 * (the_thread_awake_deliver) stores the incoming request for the 
 * taskthe_thread_awake
 */
void the_thread_awake_deliver 
    (__po_hi_request_t* request)
{

  switch (request->port)
  {
    case the_thread_awake_global_motion_in:
    {
      __po_hi_gqueue_store_in (the_controller_the_thread_awake_k, the_thread_awake_local_motion_in, request);

      break;
    }
    default:
    {
      break;
    }
  }
}


/*!
 * \fn void* the_thread_awake_job (void)
 * \brief Function executed by the task the_thread_awake
 *
 * This function is executed as soon as the task  is created. It performs the 
 * following operations:  Receive incoming data,  Execute tasks subprograms,  
 * Send output data.
 */
/*  Periodic task : the_thread_awake*/
/*  Get the IN ports values*/
void* the_thread_awake_job (void)
{
  __po_hi_request_t static motion_in_request;
  home_types__state motion_out_request_var;
  __po_hi_request_t motion_out_request;
  __po_hi_int32_t error;

  __po_hi_gqueue_init (the_controller_the_thread_awake_k, __po_hi_the_thread_awake_nb_ports, __po_hi_the_thread_awake_queue, __po_hi_the_thread_awake_fifo_size, __po_hi_the_thread_awake_first, __po_hi_the_thread_awake_offsets, __po_hi_the_thread_awake_woffsets, __po_hi_the_thread_awake_n_dest, __po_hi_the_thread_awake_destinations, __po_hi_the_thread_awake_used_size, __po_hi_the_thread_awake_history, __po_hi_the_thread_awake_recent, __po_hi_the_thread_awake_empties, __po_hi_the_thread_awake_total_fifo_size);
  
/*!
 * Waiting for other tasks initialization
 */
  __po_hi_wait_initialization ();
  __po_hi_compute_next_period (the_controller_the_thread_awake_k);
  
/*!
 * Waiting for the first dispatch instant
 */
  __po_hi_wait_for_next_period (the_controller_the_thread_awake_k);
  
/*!
 * Task body
 */
  while (1)
  {
    /* :: Yes if commentary :: */if (__po_hi_gqueue_get_count (the_controller_the_thread_awake_k, the_thread_awake_local_motion_in))
    {
          __po_hi_gqueue_get_value (the_controller_the_thread_awake_k, the_thread_awake_local_motion_in, &(motion_in_request));
      __po_hi_gqueue_next_value (the_controller_the_thread_awake_k, the_thread_awake_local_motion_in);

    }
    /*  Call implementation*/
    syst__awake_processing (motion_in_request.vars.the_thread_awake_global_motion_in.the_thread_awake_global_motion_in, &(motion_out_request_var));
    /*  Set the OUT port values*/
    motion_out_request.vars.the_thread_awake_global_motion_out.the_thread_awake_global_motion_out = motion_out_request_var;
    motion_out_request.port = the_thread_awake_global_motion_out;
    __po_hi_gqueue_store_out (the_controller_the_thread_awake_k, the_thread_awake_local_motion_out, &(motion_out_request));
    /*  Send the OUT ports*/
    error =
     __po_hi_send_output (the_controller_the_thread_awake_k, the_thread_awake_global_motion_out);
    __po_hi_wait_for_next_period (the_controller_the_thread_awake_k);
  }
}

__po_hi_port_t __po_hi_the_thread_awake_rules_coffee_out_local_destinations[1] = {the_coffee_maker_global_coffee_on_off};
__po_hi_uint8_t __po_hi_the_thread_awake_rules_woffsets[__po_hi_the_thread_awake_rules_nb_ports];
__po_hi_uint8_t __po_hi_the_thread_awake_rules_offsets[__po_hi_the_thread_awake_rules_nb_ports];
__po_hi_uint8_t __po_hi_the_thread_awake_rules_used_size[__po_hi_the_thread_awake_rules_nb_ports];
__po_hi_uint8_t __po_hi_the_thread_awake_rules_empties[__po_hi_the_thread_awake_rules_nb_ports];
__po_hi_uint8_t __po_hi_the_thread_awake_rules_first[__po_hi_the_thread_awake_rules_nb_ports];
__po_hi_request_t __po_hi_the_thread_awake_rules_recent[__po_hi_the_thread_awake_rules_nb_ports];
__po_hi_port_t __po_hi_the_thread_awake_rules_queue[0 * sizeof (__po_hi_request_t)];
__po_hi_uint16_t __po_hi_the_thread_awake_rules_total_fifo_size = 0;
__po_hi_local_port_t __po_hi_the_thread_awake_rules_history[0];
__po_hi_uint8_t __po_hi_the_thread_awake_rules_n_dest[__po_hi_the_thread_awake_rules_nb_ports] = {0,1};
__po_hi_int8_t __po_hi_the_thread_awake_rules_fifo_size[__po_hi_the_thread_awake_rules_nb_ports] = {__PO_HI_GQUEUE_FIFO_INDATA,__PO_HI_GQUEUE_FIFO_OUT};
__po_hi_port_t* __po_hi_the_thread_awake_rules_destinations[__po_hi_the_thread_awake_rules_nb_ports] = {NULL,__po_hi_the_thread_awake_rules_coffee_out_local_destinations};

/*!
 * \fn void the_thread_awake_rules_deliver (__po_hi_request_t* request)
 * \brief Function that delivers requests to the task the_thread_awake_rules
 *
 * When the generated application received a request, it calls a main delivery
 *  function that redirects to localfunctions for each task. This function 
 * (the_thread_awake_rules_deliver) stores the incoming request for the 
 * taskthe_thread_awake_rules
 */
void the_thread_awake_rules_deliver 
    (__po_hi_request_t* request)
{

  switch (request->port)
  {
    case the_thread_awake_rules_global_motion_in:
    {
      __po_hi_gqueue_store_in (the_controller_the_thread_awake_rules_k, the_thread_awake_rules_local_motion_in, request);

      break;
    }
    default:
    {
      break;
    }
  }
}


/*!
 * \fn void* the_thread_awake_rules_job (void)
 * \brief Function executed by the task the_thread_awake_rules
 *
 * This function is executed as soon as the task  is created. It performs the 
 * following operations:  Receive incoming data,  Execute tasks subprograms,  
 * Send output data.
 */
/*  Periodic task : the_thread_awake_rules*/
/*  Get the IN ports values*/
void* the_thread_awake_rules_job (void)
{
  __po_hi_request_t static motion_in_request;
  home_types__state coffee_out_request_var;
  __po_hi_request_t coffee_out_request;
  __po_hi_int32_t error;

  __po_hi_gqueue_init (the_controller_the_thread_awake_rules_k, __po_hi_the_thread_awake_rules_nb_ports, __po_hi_the_thread_awake_rules_queue, __po_hi_the_thread_awake_rules_fifo_size, __po_hi_the_thread_awake_rules_first, __po_hi_the_thread_awake_rules_offsets, __po_hi_the_thread_awake_rules_woffsets, __po_hi_the_thread_awake_rules_n_dest, __po_hi_the_thread_awake_rules_destinations, __po_hi_the_thread_awake_rules_used_size, __po_hi_the_thread_awake_rules_history, __po_hi_the_thread_awake_rules_recent, __po_hi_the_thread_awake_rules_empties, __po_hi_the_thread_awake_rules_total_fifo_size);
  
/*!
 * Waiting for other tasks initialization
 */
  __po_hi_wait_initialization ();
  __po_hi_compute_next_period (the_controller_the_thread_awake_rules_k);
  
/*!
 * Waiting for the first dispatch instant
 */
  __po_hi_wait_for_next_period (the_controller_the_thread_awake_rules_k);
  
/*!
 * Task body
 */
  while (1)
  {
    /* :: Yes if commentary :: */if (__po_hi_gqueue_get_count (the_controller_the_thread_awake_rules_k, the_thread_awake_rules_local_motion_in))
    {
          __po_hi_gqueue_get_value (the_controller_the_thread_awake_rules_k, the_thread_awake_rules_local_motion_in, &(motion_in_request));
      __po_hi_gqueue_next_value (the_controller_the_thread_awake_rules_k, the_thread_awake_rules_local_motion_in);

    }
    /*  Call implementation*/
    syst__awake_processing_rules (motion_in_request.vars.the_thread_awake_rules_global_motion_in.the_thread_awake_rules_global_motion_in, &(coffee_out_request_var));
    /*  Set the OUT port values*/
    coffee_out_request.vars.the_thread_awake_rules_global_coffee_out.the_thread_awake_rules_global_coffee_out = coffee_out_request_var;
    coffee_out_request.port = the_thread_awake_rules_global_coffee_out;
    __po_hi_gqueue_store_out (the_controller_the_thread_awake_rules_k, the_thread_awake_rules_local_coffee_out, &(coffee_out_request));
    /*  Send the OUT ports*/
    error =
     __po_hi_send_output (the_controller_the_thread_awake_rules_k, the_thread_awake_rules_global_coffee_out);
    __po_hi_wait_for_next_period (the_controller_the_thread_awake_rules_k);
  }
}

__po_hi_port_t __po_hi_the_thread_video_video_out_local_destinations[1] = {the_security_global_video_in};
__po_hi_port_t __po_hi_the_thread_video_video_not_recognized_local_destinations[1] = {the_thread_control_global_video_not_recognized};
__po_hi_uint8_t __po_hi_the_thread_video_woffsets[__po_hi_the_thread_video_nb_ports];
__po_hi_uint8_t __po_hi_the_thread_video_offsets[__po_hi_the_thread_video_nb_ports];
__po_hi_uint8_t __po_hi_the_thread_video_used_size[__po_hi_the_thread_video_nb_ports];
__po_hi_uint8_t __po_hi_the_thread_video_empties[__po_hi_the_thread_video_nb_ports];
__po_hi_uint8_t __po_hi_the_thread_video_first[__po_hi_the_thread_video_nb_ports];
__po_hi_request_t __po_hi_the_thread_video_recent[__po_hi_the_thread_video_nb_ports];
__po_hi_port_t __po_hi_the_thread_video_queue[0 * sizeof (__po_hi_request_t)];
__po_hi_uint16_t __po_hi_the_thread_video_total_fifo_size = 0;
__po_hi_local_port_t __po_hi_the_thread_video_history[0];
__po_hi_uint8_t __po_hi_the_thread_video_n_dest[__po_hi_the_thread_video_nb_ports] = {0,1,1};
__po_hi_int8_t __po_hi_the_thread_video_fifo_size[__po_hi_the_thread_video_nb_ports] = {__PO_HI_GQUEUE_FIFO_INDATA,__PO_HI_GQUEUE_FIFO_OUT,__PO_HI_GQUEUE_FIFO_OUT};
__po_hi_port_t* __po_hi_the_thread_video_destinations[__po_hi_the_thread_video_nb_ports] = {NULL,__po_hi_the_thread_video_video_out_local_destinations,__po_hi_the_thread_video_video_not_recognized_local_destinations};

/*!
 * \fn void the_thread_video_deliver (__po_hi_request_t* request)
 * \brief Function that delivers requests to the task the_thread_video
 *
 * When the generated application received a request, it calls a main delivery
 *  function that redirects to localfunctions for each task. This function 
 * (the_thread_video_deliver) stores the incoming request for the 
 * taskthe_thread_video
 */
void the_thread_video_deliver 
    (__po_hi_request_t* request)
{

  switch (request->port)
  {
    case the_thread_video_global_video_in:
    {
      __po_hi_gqueue_store_in (the_controller_the_thread_video_k, the_thread_video_local_video_in, request);

      break;
    }
    default:
    {
      break;
    }
  }
}


/*!
 * \fn void* the_thread_video_job (void)
 * \brief Function executed by the task the_thread_video
 *
 * This function is executed as soon as the task  is created. It performs the 
 * following operations:  Receive incoming data,  Execute tasks subprograms,  
 * Send output data.
 */
/*  Periodic task : the_thread_video*/
/*  Get the IN ports values*/
void* the_thread_video_job (void)
{
  __po_hi_request_t static video_in_request;
  home_types__state video_out_request_var;
  home_types__state video_not_recognized_request_var;
  __po_hi_request_t video_out_request;
  __po_hi_request_t video_not_recognized_request;
  __po_hi_int32_t error;

  __po_hi_gqueue_init (the_controller_the_thread_video_k, __po_hi_the_thread_video_nb_ports, __po_hi_the_thread_video_queue, __po_hi_the_thread_video_fifo_size, __po_hi_the_thread_video_first, __po_hi_the_thread_video_offsets, __po_hi_the_thread_video_woffsets, __po_hi_the_thread_video_n_dest, __po_hi_the_thread_video_destinations, __po_hi_the_thread_video_used_size, __po_hi_the_thread_video_history, __po_hi_the_thread_video_recent, __po_hi_the_thread_video_empties, __po_hi_the_thread_video_total_fifo_size);
  
/*!
 * Waiting for other tasks initialization
 */
  __po_hi_wait_initialization ();
  __po_hi_compute_next_period (the_controller_the_thread_video_k);
  
/*!
 * Waiting for the first dispatch instant
 */
  __po_hi_wait_for_next_period (the_controller_the_thread_video_k);
  
/*!
 * Task body
 */
  while (1)
  {
    /* :: Yes if commentary :: */if (__po_hi_gqueue_get_count (the_controller_the_thread_video_k, the_thread_video_local_video_in))
    {
          __po_hi_gqueue_get_value (the_controller_the_thread_video_k, the_thread_video_local_video_in, &(video_in_request));
      __po_hi_gqueue_next_value (the_controller_the_thread_video_k, the_thread_video_local_video_in);

    }
    /*  Call implementation*/
    syst__video_processing (video_in_request.vars.the_thread_video_global_video_in.the_thread_video_global_video_in, &(video_out_request_var), &(video_not_recognized_request_var));
    /*  Set the OUT port values*/
    video_out_request.vars.the_thread_video_global_video_out.the_thread_video_global_video_out = video_out_request_var;
    video_out_request.port = the_thread_video_global_video_out;
    __po_hi_gqueue_store_out (the_controller_the_thread_video_k, the_thread_video_local_video_out, &(video_out_request));
    video_not_recognized_request.vars.the_thread_video_global_video_not_recognized.the_thread_video_global_video_not_recognized = video_not_recognized_request_var;
    video_not_recognized_request.port = the_thread_video_global_video_not_recognized;
    __po_hi_gqueue_store_out (the_controller_the_thread_video_k, the_thread_video_local_video_not_recognized, &(video_not_recognized_request));
    /*  Send the OUT ports*/
    error =
     __po_hi_send_output (the_controller_the_thread_video_k, the_thread_video_global_video_out);
    error =
     __po_hi_send_output (the_controller_the_thread_video_k, the_thread_video_global_video_not_recognized);
    __po_hi_wait_for_next_period (the_controller_the_thread_video_k);
  }
}

__po_hi_port_t __po_hi_the_thread_car_motion_out_local_destinations[1] = {the_thread_control_global_gate_in};
__po_hi_uint8_t __po_hi_the_thread_car_woffsets[__po_hi_the_thread_car_nb_ports];
__po_hi_uint8_t __po_hi_the_thread_car_offsets[__po_hi_the_thread_car_nb_ports];
__po_hi_uint8_t __po_hi_the_thread_car_used_size[__po_hi_the_thread_car_nb_ports];
__po_hi_uint8_t __po_hi_the_thread_car_empties[__po_hi_the_thread_car_nb_ports];
__po_hi_uint8_t __po_hi_the_thread_car_first[__po_hi_the_thread_car_nb_ports];
__po_hi_request_t __po_hi_the_thread_car_recent[__po_hi_the_thread_car_nb_ports];
__po_hi_port_t __po_hi_the_thread_car_queue[0 * sizeof (__po_hi_request_t)];
__po_hi_uint16_t __po_hi_the_thread_car_total_fifo_size = 0;
__po_hi_local_port_t __po_hi_the_thread_car_history[0];
__po_hi_uint8_t __po_hi_the_thread_car_n_dest[__po_hi_the_thread_car_nb_ports] = {0,1};
__po_hi_int8_t __po_hi_the_thread_car_fifo_size[__po_hi_the_thread_car_nb_ports] = {__PO_HI_GQUEUE_FIFO_INDATA,__PO_HI_GQUEUE_FIFO_OUT};
__po_hi_port_t* __po_hi_the_thread_car_destinations[__po_hi_the_thread_car_nb_ports] = {NULL,__po_hi_the_thread_car_motion_out_local_destinations};

/*!
 * \fn void the_thread_car_deliver (__po_hi_request_t* request)
 * \brief Function that delivers requests to the task the_thread_car
 *
 * When the generated application received a request, it calls a main delivery
 *  function that redirects to localfunctions for each task. This function 
 * (the_thread_car_deliver) stores the incoming request for the 
 * taskthe_thread_car
 */
void the_thread_car_deliver 
    (__po_hi_request_t* request)
{

  switch (request->port)
  {
    case the_thread_car_global_motion_in:
    {
      __po_hi_gqueue_store_in (the_controller_the_thread_car_k, the_thread_car_local_motion_in, request);

      break;
    }
    default:
    {
      break;
    }
  }
}


/*!
 * \fn void* the_thread_car_job (void)
 * \brief Function executed by the task the_thread_car
 *
 * This function is executed as soon as the task  is created. It performs the 
 * following operations:  Receive incoming data,  Execute tasks subprograms,  
 * Send output data.
 */
/*  Periodic task : the_thread_car*/
/*  Get the IN ports values*/
void* the_thread_car_job (void)
{
  __po_hi_request_t static motion_in_request;
  home_types__state car_detected_request_var;
  __po_hi_request_t motion_out_request;
  __po_hi_int32_t error;

  __po_hi_gqueue_init (the_controller_the_thread_car_k, __po_hi_the_thread_car_nb_ports, __po_hi_the_thread_car_queue, __po_hi_the_thread_car_fifo_size, __po_hi_the_thread_car_first, __po_hi_the_thread_car_offsets, __po_hi_the_thread_car_woffsets, __po_hi_the_thread_car_n_dest, __po_hi_the_thread_car_destinations, __po_hi_the_thread_car_used_size, __po_hi_the_thread_car_history, __po_hi_the_thread_car_recent, __po_hi_the_thread_car_empties, __po_hi_the_thread_car_total_fifo_size);
  
/*!
 * Waiting for other tasks initialization
 */
  __po_hi_wait_initialization ();
  __po_hi_compute_next_period (the_controller_the_thread_car_k);
  
/*!
 * Waiting for the first dispatch instant
 */
  __po_hi_wait_for_next_period (the_controller_the_thread_car_k);
  
/*!
 * Task body
 */
  while (1)
  {
    /* :: Yes if commentary :: */if (__po_hi_gqueue_get_count (the_controller_the_thread_car_k, the_thread_car_local_motion_in))
    {
          __po_hi_gqueue_get_value (the_controller_the_thread_car_k, the_thread_car_local_motion_in, &(motion_in_request));
      __po_hi_gqueue_next_value (the_controller_the_thread_car_k, the_thread_car_local_motion_in);

    }
    /*  Call implementation*/
    syst__car_processing (motion_in_request.vars.the_thread_car_global_motion_in.the_thread_car_global_motion_in, &(car_detected_request_var));
    /*  Set the OUT port values*/
    motion_out_request.vars.the_thread_car_global_motion_out.the_thread_car_global_motion_out = motion_out_request_var;
    motion_out_request.port = the_thread_car_global_motion_out;
    __po_hi_gqueue_store_out (the_controller_the_thread_car_k, the_thread_car_local_motion_out, &(motion_out_request));
    /*  Send the OUT ports*/
    error =
     __po_hi_send_output (the_controller_the_thread_car_k, the_thread_car_global_motion_out);
    __po_hi_wait_for_next_period (the_controller_the_thread_car_k);
  }
}


/*!
 * \fn void __po_hi_main_deliver (__po_hi_request_t* request)
 * \brief Used to deliver request to the appropriate ports
 *
 * This function takes a request as argument (\arg request) and calls the 
 * appropriate function for its delivery.To specify which function should be 
 * called, it extracts the receiver entity using the destination port.
 */
void __po_hi_main_deliver 
    (__po_hi_request_t* request)
{
  __po_hi_entity_t entity;

  entity = __po_hi_get_entity_from_global_port (request->port);
  switch (entity)
  {
    case the_controller_the_thread_motion_k_entity:
    {
      the_thread_motion_deliver (request);

      break;
    }
    case the_controller_the_thread_control_k_entity:
    {
      the_thread_control_deliver (request);

      break;
    }
    case the_controller_the_thread_awake_k_entity:
    {
      the_thread_awake_deliver (request);

      break;
    }
    case the_controller_the_thread_awake_rules_k_entity:
    {
      the_thread_awake_rules_deliver (request);

      break;
    }
    case the_controller_the_thread_video_k_entity:
    {
      the_thread_video_deliver (request);

      break;
    }
    case the_controller_the_thread_car_k_entity:
    {
      the_thread_car_deliver (request);

      break;
    }
    default:
    {
      break;
    }
  }
}


