#ifndef __OCARINA_GENERATED_DEPLOYMENT_H_
#define __OCARINA_GENERATED_DEPLOYMENT_H_ 
#include <po_hi_types.h>
/*****************************************************/

/*  This file was automatically generated by Ocarina */

/*  Do NOT hand-modify this file, as your            */

/*  changes will be lost when you re-run Ocarina     */

/*****************************************************/

#define __PO_HI_MY_NODE the_controller_k

#define __po_hi_the_thread_motion_nb_ports 2

#define __po_hi_the_thread_control_nb_ports 9

#define __po_hi_the_thread_awake_nb_ports 2

#define __po_hi_the_thread_awake_rules_nb_ports 2

#define __po_hi_the_thread_video_nb_ports 3

#define __po_hi_the_thread_car_nb_ports 2

/*  For each node in the distributed application add an enumerator*/

typedef enum
{
  the_controller_k = 0
} __po_hi_node_t;

typedef enum
{
  invalid_protocol = -1
} __po_hi_protocol_t;

/*  For each thread in the distributed application nodes, add an enumerator*/

typedef enum
{
  the_controller_the_thread_motion_k_entity = 0,
  the_controller_the_thread_control_k_entity = 1,
  the_controller_the_thread_awake_k_entity = 2,
  the_controller_the_thread_awake_rules_k_entity = 3,
  the_controller_the_thread_video_k_entity = 4,
  the_controller_the_thread_car_k_entity = 5,
  invalid_entity = -1
} __po_hi_entity_t;

typedef enum
{
  the_controller_the_thread_motion_k = 0,
  the_controller_the_thread_control_k = 1,
  the_controller_the_thread_awake_k = 2,
  the_controller_the_thread_awake_rules_k = 3,
  the_controller_the_thread_video_k = 4,
  the_controller_the_thread_car_k = 5,
  invalid_task_id = -1
} __po_hi_task_id;

typedef enum
{
  invalid_device_id = -1
} __po_hi_device_id;

typedef enum
{
  invalid_bus_id = -1,
  bus_the_bus = 0
} __po_hi_bus_id;

#define __PO_HI_NB_TASKS 6

#define __PO_HI_TASKS_STACK 0

#define __PO_HI_NB_PROTECTED 0

#define __PO_HI_NB_NODES 1

#define __PO_HI_NB_ENTITIES 6

#define __PO_HI_NB_PORTS 20

typedef enum
{
  the_thread_motion_global_motion_in = 0,
  the_thread_motion_global_motion_out = 1,
  the_thread_control_global_video_not_recognized = 2,
  the_thread_control_global_motion_in = 3,
  the_thread_control_global_camera_out = 4,
  the_thread_control_global_light_out = 5,
  the_thread_control_global_heat_out = 6,
  the_thread_control_global_music_out = 7,
  the_thread_control_global_alarm_out = 8,
  the_thread_control_global_gate_in = 9,
  the_thread_control_global_gate_out = 10,
  the_thread_awake_global_motion_in = 11,
  the_thread_awake_global_motion_out = 12,
  the_thread_awake_rules_global_motion_in = 13,
  the_thread_awake_rules_global_coffee_out = 14,
  the_thread_video_global_video_in = 15,
  the_thread_video_global_video_out = 16,
  the_thread_video_global_video_not_recognized = 17,
  the_thread_car_global_motion_in = 18,
  the_thread_car_global_motion_out = 19,
  invalid_port_t = -1,
  constant_out_identifier = 21
} __po_hi_port_t;

typedef enum
{
  the_thread_motion_local_motion_in = 0,
  the_thread_motion_local_motion_out = 1,
  the_thread_control_local_video_not_recognized = 0,
  the_thread_control_local_motion_in = 1,
  the_thread_control_local_camera_out = 2,
  the_thread_control_local_light_out = 3,
  the_thread_control_local_heat_out = 4,
  the_thread_control_local_music_out = 5,
  the_thread_control_local_alarm_out = 6,
  the_thread_control_local_gate_in = 7,
  the_thread_control_local_gate_out = 8,
  the_thread_awake_local_motion_in = 0,
  the_thread_awake_local_motion_out = 1,
  the_thread_awake_rules_local_motion_in = 0,
  the_thread_awake_rules_local_coffee_out = 1,
  the_thread_video_local_video_in = 0,
  the_thread_video_local_video_out = 1,
  the_thread_video_local_video_not_recognized = 2,
  the_thread_car_local_motion_in = 0,
  the_thread_car_local_motion_out = 1,
  invalid_local_port_t = -1
} __po_hi_local_port_t;

#define __PO_HI_NB_DEVICES 0

#define __PO_HI_NB_BUSES 1

#define __PO_HI_NB_PROTOCOLS 0

#define __PO_HI_PORT_TYPE_CONTENT __po_hi_the_thread_motion_nb_ports, __po_hi_the_thread_control_nb_ports, __po_hi_the_thread_awake_nb_ports, __po_hi_the_thread_awake_rules_nb_ports, __po_hi_the_thread_video_nb_ports, __po_hi_the_thread_car_nb_ports

#endif
