#include <activity.h>
#include <po_hi_task.h>
#include <po_hi_main.h>
#include <drivers/po_hi_driver_sockets.h>
#include <po_hi_time.h>
/*****************************************************/
/*  This file was automatically generated by Ocarina */
/*  Do NOT hand-modify this file, as your            */
/*  changes will be lost when you re-run Ocarina     */
/*****************************************************/

/*!
 * \fn __PO_HI_MAIN_TYPE __PO_HI_MAIN_NAME (void)
 * \brief Main function executed by the system
 *
 * Full function name and return types are available  in the PolyORB-HI-C 
 * runtime header files.
 */
__PO_HI_MAIN_TYPE __PO_HI_MAIN_NAME (void)
{
  
/*!
 * \var period
 * \brief Variable for task period
 *
 * This variable is used to store the valueof the period of a task when we 
 * create it. The value put in the variable is set according to AADL model 
 * description
 */
  __po_hi_time_t period;

  __po_hi_initialize_early ();
  
/*!
 * Initialize the runtime
 */
  __po_hi_initialize ();
  __po_hi_driver_sockets_init (0);
  
/*!
 * Store the period time for task the_thread_motion
 */
  __po_hi_milliseconds (&(period), 500);
  
/*!
 * \brief Making Periodic Task the_thread_motion
 *
 * Make a periodic task according to AADL model requirements. The first 
 * parameter is the task identifier defined in deployment.h 
 * (the_controller_the_thread_motion_k) the second is the period defined in 
 * the AADL model. Third is the task priority ( 10), fourth is the stack 
 * size ( 0 bytes) and last is the subprogram executed by the task
 */
  __po_hi_create_periodic_task (the_controller_the_thread_motion_k, &(period), 10, 0, 0, the_thread_motion_job);
  
/*!
 * Store the period time for task the_thread_control
 */
  __po_hi_milliseconds (&(period), 100);
  
/*!
 * \brief Making Periodic Task the_thread_control
 *
 * Make a periodic task according to AADL model requirements. The first 
 * parameter is the task identifier defined in deployment.h 
 * (the_controller_the_thread_control_k) the second is the period defined in
 *  the AADL model. Third is the task priority ( 9), fourth is the stack 
 * size ( 0 bytes) and last is the subprogram executed by the task
 */
  __po_hi_create_periodic_task (the_controller_the_thread_control_k, &(period), 9, 0, 0, the_thread_control_job);
  
/*!
 * Store the period time for task the_thread_awake
 */
  __po_hi_milliseconds (&(period), 300000);
  
/*!
 * \brief Making Periodic Task the_thread_awake
 *
 * Make a periodic task according to AADL model requirements. The first 
 * parameter is the task identifier defined in deployment.h 
 * (the_controller_the_thread_awake_k) the second is the period defined in 
 * the AADL model. Third is the task priority ( 3), fourth is the stack size
 *  ( 0 bytes) and last is the subprogram executed by the task
 */
  __po_hi_create_periodic_task (the_controller_the_thread_awake_k, &(period), 3, 0, 0, the_thread_awake_job);
  
/*!
 * Store the period time for task the_thread_awake_rules
 */
  __po_hi_milliseconds (&(period), 10000);
  
/*!
 * \brief Making Periodic Task the_thread_awake_rules
 *
 * Make a periodic task according to AADL model requirements. The first 
 * parameter is the task identifier defined in deployment.h 
 * (the_controller_the_thread_awake_rules_k) the second is the period 
 * defined in the AADL model. Third is the task priority ( 0), fourth is the
 *  stack size ( 0 bytes) and last is the subprogram executed by the task
 */
  __po_hi_create_periodic_task (the_controller_the_thread_awake_rules_k, &(period), __PO_HI_DEFAULT_PRIORITY, 0, 0, the_thread_awake_rules_job);
  
/*!
 * Store the period time for task the_thread_video
 */
  __po_hi_milliseconds (&(period), 1000);
  
/*!
 * \brief Making Periodic Task the_thread_video
 *
 * Make a periodic task according to AADL model requirements. The first 
 * parameter is the task identifier defined in deployment.h 
 * (the_controller_the_thread_video_k) the second is the period defined in 
 * the AADL model. Third is the task priority ( 7), fourth is the stack size
 *  ( 0 bytes) and last is the subprogram executed by the task
 */
  __po_hi_create_periodic_task (the_controller_the_thread_video_k, &(period), 7, 0, 0, the_thread_video_job);
  
/*!
 * Store the period time for task the_thread_car
 */
  __po_hi_milliseconds (&(period), 5000);
  
/*!
 * \brief Making Periodic Task the_thread_car
 *
 * Make a periodic task according to AADL model requirements. The first 
 * parameter is the task identifier defined in deployment.h 
 * (the_controller_the_thread_car_k) the second is the period defined in the
 *  AADL model. Third is the task priority ( 6), fourth is the stack size ( 
 * 0 bytes) and last is the subprogram executed by the task
 */
  __po_hi_create_periodic_task (the_controller_the_thread_car_k, &(period), 6, 0, 0, the_thread_car_job);
  
/*!
 * Waiting for other tasks initialization
 */
  __po_hi_wait_initialization ();
  
/*!
 * Used to switch the main task to sleep all the time
 */
  __po_hi_wait_for_tasks ();
  
/*!
 * Return Statement
 */
  return (__PO_HI_MAIN_RETURN);
}


