#include <types.h>
#include <po_hi_types.h>
#include <po_hi_marshallers.h>
/*****************************************************/
/*  This file was automatically generated by Ocarina */
/*  Do NOT hand-modify this file, as your            */
/*  changes will be lost when you re-run Ocarina     */
/*****************************************************/
void __po_hi_marshall_type_motion_state 
    (home_types__motion_state value,
    __po_hi_msg_t* message,
    __po_hi_uint32_t* offset)
{

  __po_hi_marshall_int (value, message, offset);
}

void __po_hi_unmarshall_type_motion_state 
    (home_types__motion_state* value,
    __po_hi_msg_t* message,
    __po_hi_uint32_t* offset)
{

  __po_hi_unmarshall_int (value, message, offset);
}

void __po_hi_marshall_request_the_thread_motion_motion_in 
    (__po_hi_request_t* request,
    __po_hi_msg_t* message,
    __po_hi_uint32_t* offset)
{

  __po_hi_marshall_type_motion_state (request->vars.the_thread_motion_global_motion_in.the_thread_motion_global_motion_in, message, offset);
}

void __po_hi_unmarshall_request_the_thread_motion_motion_in 
    (__po_hi_request_t* request,
    __po_hi_msg_t* message,
    __po_hi_uint32_t* offset)
{

  __po_hi_unmarshall_type_motion_state (&(request->vars.the_thread_motion_global_motion_in.the_thread_motion_global_motion_in), message, offset);
}

void __po_hi_marshall_request_the_thread_motion_motion_out 
    (__po_hi_request_t* request,
    __po_hi_msg_t* message,
    __po_hi_uint32_t* offset)
{

  __po_hi_marshall_type_motion_state (request->vars.the_thread_motion_global_motion_out.the_thread_motion_global_motion_out, message, offset);
}

void __po_hi_unmarshall_request_the_thread_motion_motion_out 
    (__po_hi_request_t* request,
    __po_hi_msg_t* message,
    __po_hi_uint32_t* offset)
{

  __po_hi_unmarshall_type_motion_state (&(request->vars.the_thread_motion_global_motion_out.the_thread_motion_global_motion_out), message, offset);
}

void __po_hi_marshall_request_the_thread_control_video_not_recognized 
    (__po_hi_request_t* request,
    __po_hi_msg_t* message,
    __po_hi_uint32_t* offset)
{

  __po_hi_marshall_type_motion_state (request->vars.the_thread_control_global_video_not_recognized.the_thread_control_global_video_not_recognized, message, offset);
}

void __po_hi_unmarshall_request_the_thread_control_video_not_recognized 
    (__po_hi_request_t* request,
    __po_hi_msg_t* message,
    __po_hi_uint32_t* offset)
{

  __po_hi_unmarshall_type_motion_state (&(request->vars.the_thread_control_global_video_not_recognized.the_thread_control_global_video_not_recognized), message, offset);
}

void __po_hi_marshall_request_the_thread_control_motion_in 
    (__po_hi_request_t* request,
    __po_hi_msg_t* message,
    __po_hi_uint32_t* offset)
{

  __po_hi_marshall_type_motion_state (request->vars.the_thread_control_global_motion_in.the_thread_control_global_motion_in, message, offset);
}

void __po_hi_unmarshall_request_the_thread_control_motion_in 
    (__po_hi_request_t* request,
    __po_hi_msg_t* message,
    __po_hi_uint32_t* offset)
{

  __po_hi_unmarshall_type_motion_state (&(request->vars.the_thread_control_global_motion_in.the_thread_control_global_motion_in), message, offset);
}

void __po_hi_marshall_request_the_thread_control_camera_out 
    (__po_hi_request_t* request,
    __po_hi_msg_t* message,
    __po_hi_uint32_t* offset)
{

  __po_hi_marshall_type_motion_state (request->vars.the_thread_control_global_camera_out.the_thread_control_global_camera_out, message, offset);
}

void __po_hi_unmarshall_request_the_thread_control_camera_out 
    (__po_hi_request_t* request,
    __po_hi_msg_t* message,
    __po_hi_uint32_t* offset)
{

  __po_hi_unmarshall_type_motion_state (&(request->vars.the_thread_control_global_camera_out.the_thread_control_global_camera_out), message, offset);
}

void __po_hi_marshall_request_the_thread_control_light_out 
    (__po_hi_request_t* request,
    __po_hi_msg_t* message,
    __po_hi_uint32_t* offset)
{

  __po_hi_marshall_type_motion_state (request->vars.the_thread_control_global_light_out.the_thread_control_global_light_out, message, offset);
}

void __po_hi_unmarshall_request_the_thread_control_light_out 
    (__po_hi_request_t* request,
    __po_hi_msg_t* message,
    __po_hi_uint32_t* offset)
{

  __po_hi_unmarshall_type_motion_state (&(request->vars.the_thread_control_global_light_out.the_thread_control_global_light_out), message, offset);
}

void __po_hi_marshall_request_the_thread_control_heat_out 
    (__po_hi_request_t* request,
    __po_hi_msg_t* message,
    __po_hi_uint32_t* offset)
{

  __po_hi_marshall_type_motion_state (request->vars.the_thread_control_global_heat_out.the_thread_control_global_heat_out, message, offset);
}

void __po_hi_unmarshall_request_the_thread_control_heat_out 
    (__po_hi_request_t* request,
    __po_hi_msg_t* message,
    __po_hi_uint32_t* offset)
{

  __po_hi_unmarshall_type_motion_state (&(request->vars.the_thread_control_global_heat_out.the_thread_control_global_heat_out), message, offset);
}

void __po_hi_marshall_request_the_thread_control_music_out 
    (__po_hi_request_t* request,
    __po_hi_msg_t* message,
    __po_hi_uint32_t* offset)
{

  __po_hi_marshall_type_motion_state (request->vars.the_thread_control_global_music_out.the_thread_control_global_music_out, message, offset);
}

void __po_hi_unmarshall_request_the_thread_control_music_out 
    (__po_hi_request_t* request,
    __po_hi_msg_t* message,
    __po_hi_uint32_t* offset)
{

  __po_hi_unmarshall_type_motion_state (&(request->vars.the_thread_control_global_music_out.the_thread_control_global_music_out), message, offset);
}

void __po_hi_marshall_request_the_thread_control_alarm_out 
    (__po_hi_request_t* request,
    __po_hi_msg_t* message,
    __po_hi_uint32_t* offset)
{

  __po_hi_marshall_type_motion_state (request->vars.the_thread_control_global_alarm_out.the_thread_control_global_alarm_out, message, offset);
}

void __po_hi_unmarshall_request_the_thread_control_alarm_out 
    (__po_hi_request_t* request,
    __po_hi_msg_t* message,
    __po_hi_uint32_t* offset)
{

  __po_hi_unmarshall_type_motion_state (&(request->vars.the_thread_control_global_alarm_out.the_thread_control_global_alarm_out), message, offset);
}

void __po_hi_marshall_request_the_thread_control_gate_in 
    (__po_hi_request_t* request,
    __po_hi_msg_t* message,
    __po_hi_uint32_t* offset)
{

  __po_hi_marshall_type_motion_state (request->vars.the_thread_control_global_gate_in.the_thread_control_global_gate_in, message, offset);
}

void __po_hi_unmarshall_request_the_thread_control_gate_in 
    (__po_hi_request_t* request,
    __po_hi_msg_t* message,
    __po_hi_uint32_t* offset)
{

  __po_hi_unmarshall_type_motion_state (&(request->vars.the_thread_control_global_gate_in.the_thread_control_global_gate_in), message, offset);
}

void __po_hi_marshall_request_the_thread_control_gate_out 
    (__po_hi_request_t* request,
    __po_hi_msg_t* message,
    __po_hi_uint32_t* offset)
{

  __po_hi_marshall_type_motion_state (request->vars.the_thread_control_global_gate_out.the_thread_control_global_gate_out, message, offset);
}

void __po_hi_unmarshall_request_the_thread_control_gate_out 
    (__po_hi_request_t* request,
    __po_hi_msg_t* message,
    __po_hi_uint32_t* offset)
{

  __po_hi_unmarshall_type_motion_state (&(request->vars.the_thread_control_global_gate_out.the_thread_control_global_gate_out), message, offset);
}

void __po_hi_marshall_request_the_thread_awake_motion_in 
    (__po_hi_request_t* request,
    __po_hi_msg_t* message,
    __po_hi_uint32_t* offset)
{

  __po_hi_marshall_type_motion_state (request->vars.the_thread_awake_global_motion_in.the_thread_awake_global_motion_in, message, offset);
}

void __po_hi_unmarshall_request_the_thread_awake_motion_in 
    (__po_hi_request_t* request,
    __po_hi_msg_t* message,
    __po_hi_uint32_t* offset)
{

  __po_hi_unmarshall_type_motion_state (&(request->vars.the_thread_awake_global_motion_in.the_thread_awake_global_motion_in), message, offset);
}

void __po_hi_marshall_request_the_thread_awake_motion_out 
    (__po_hi_request_t* request,
    __po_hi_msg_t* message,
    __po_hi_uint32_t* offset)
{

  __po_hi_marshall_type_motion_state (request->vars.the_thread_awake_global_motion_out.the_thread_awake_global_motion_out, message, offset);
}

void __po_hi_unmarshall_request_the_thread_awake_motion_out 
    (__po_hi_request_t* request,
    __po_hi_msg_t* message,
    __po_hi_uint32_t* offset)
{

  __po_hi_unmarshall_type_motion_state (&(request->vars.the_thread_awake_global_motion_out.the_thread_awake_global_motion_out), message, offset);
}

void __po_hi_marshall_request_the_thread_awake_rules_motion_in 
    (__po_hi_request_t* request,
    __po_hi_msg_t* message,
    __po_hi_uint32_t* offset)
{

  __po_hi_marshall_type_motion_state (request->vars.the_thread_awake_rules_global_motion_in.the_thread_awake_rules_global_motion_in, message, offset);
}

void __po_hi_unmarshall_request_the_thread_awake_rules_motion_in 
    (__po_hi_request_t* request,
    __po_hi_msg_t* message,
    __po_hi_uint32_t* offset)
{

  __po_hi_unmarshall_type_motion_state (&(request->vars.the_thread_awake_rules_global_motion_in.the_thread_awake_rules_global_motion_in), message, offset);
}

void __po_hi_marshall_request_the_thread_awake_rules_coffee_out 
    (__po_hi_request_t* request,
    __po_hi_msg_t* message,
    __po_hi_uint32_t* offset)
{

  __po_hi_marshall_type_motion_state (request->vars.the_thread_awake_rules_global_coffee_out.the_thread_awake_rules_global_coffee_out, message, offset);
}

void __po_hi_unmarshall_request_the_thread_awake_rules_coffee_out 
    (__po_hi_request_t* request,
    __po_hi_msg_t* message,
    __po_hi_uint32_t* offset)
{

  __po_hi_unmarshall_type_motion_state (&(request->vars.the_thread_awake_rules_global_coffee_out.the_thread_awake_rules_global_coffee_out), message, offset);
}

void __po_hi_marshall_request_the_thread_video_video_in 
    (__po_hi_request_t* request,
    __po_hi_msg_t* message,
    __po_hi_uint32_t* offset)
{

  __po_hi_marshall_type_motion_state (request->vars.the_thread_video_global_video_in.the_thread_video_global_video_in, message, offset);
}

void __po_hi_unmarshall_request_the_thread_video_video_in 
    (__po_hi_request_t* request,
    __po_hi_msg_t* message,
    __po_hi_uint32_t* offset)
{

  __po_hi_unmarshall_type_motion_state (&(request->vars.the_thread_video_global_video_in.the_thread_video_global_video_in), message, offset);
}

void __po_hi_marshall_request_the_thread_video_video_out 
    (__po_hi_request_t* request,
    __po_hi_msg_t* message,
    __po_hi_uint32_t* offset)
{

  __po_hi_marshall_type_motion_state (request->vars.the_thread_video_global_video_out.the_thread_video_global_video_out, message, offset);
}

void __po_hi_unmarshall_request_the_thread_video_video_out 
    (__po_hi_request_t* request,
    __po_hi_msg_t* message,
    __po_hi_uint32_t* offset)
{

  __po_hi_unmarshall_type_motion_state (&(request->vars.the_thread_video_global_video_out.the_thread_video_global_video_out), message, offset);
}

void __po_hi_marshall_request_the_thread_video_video_not_recognized 
    (__po_hi_request_t* request,
    __po_hi_msg_t* message,
    __po_hi_uint32_t* offset)
{

  __po_hi_marshall_type_motion_state (request->vars.the_thread_video_global_video_not_recognized.the_thread_video_global_video_not_recognized, message, offset);
}

void __po_hi_unmarshall_request_the_thread_video_video_not_recognized 
    (__po_hi_request_t* request,
    __po_hi_msg_t* message,
    __po_hi_uint32_t* offset)
{

  __po_hi_unmarshall_type_motion_state (&(request->vars.the_thread_video_global_video_not_recognized.the_thread_video_global_video_not_recognized), message, offset);
}

void __po_hi_marshall_request_the_thread_car_motion_in 
    (__po_hi_request_t* request,
    __po_hi_msg_t* message,
    __po_hi_uint32_t* offset)
{

  __po_hi_marshall_type_motion_state (request->vars.the_thread_car_global_motion_in.the_thread_car_global_motion_in, message, offset);
}

void __po_hi_unmarshall_request_the_thread_car_motion_in 
    (__po_hi_request_t* request,
    __po_hi_msg_t* message,
    __po_hi_uint32_t* offset)
{

  __po_hi_unmarshall_type_motion_state (&(request->vars.the_thread_car_global_motion_in.the_thread_car_global_motion_in), message, offset);
}

void __po_hi_marshall_request_the_thread_car_motion_out 
    (__po_hi_request_t* request,
    __po_hi_msg_t* message,
    __po_hi_uint32_t* offset)
{

  __po_hi_marshall_type_motion_state (request->vars.the_thread_car_global_motion_out.the_thread_car_global_motion_out, message, offset);
}

void __po_hi_unmarshall_request_the_thread_car_motion_out 
    (__po_hi_request_t* request,
    __po_hi_msg_t* message,
    __po_hi_uint32_t* offset)
{

  __po_hi_unmarshall_type_motion_state (&(request->vars.the_thread_car_global_motion_out.the_thread_car_global_motion_out), message, offset);
}

void __po_hi_marshall_request 
    (__po_hi_request_t* request,
    __po_hi_msg_t* message)
{
  __po_hi_uint32_t offset;

  offset = 0;
  __po_hi_marshall_port (request->port, message);
  switch (request->port)
  {
    case the_thread_motion_global_motion_in:
    {
      __po_hi_marshall_request_the_thread_motion_motion_in (request, message, &(offset));

      break;
    }
    case the_thread_motion_global_motion_out:
    {
      __po_hi_marshall_request_the_thread_motion_motion_out (request, message, &(offset));

      break;
    }
    case the_thread_control_global_video_not_recognized:
    {
      __po_hi_marshall_request_the_thread_control_video_not_recognized (request, message, &(offset));

      break;
    }
    case the_thread_control_global_motion_in:
    {
      __po_hi_marshall_request_the_thread_control_motion_in (request, message, &(offset));

      break;
    }
    case the_thread_control_global_camera_out:
    {
      __po_hi_marshall_request_the_thread_control_camera_out (request, message, &(offset));

      break;
    }
    case the_thread_control_global_light_out:
    {
      __po_hi_marshall_request_the_thread_control_light_out (request, message, &(offset));

      break;
    }
    case the_thread_control_global_heat_out:
    {
      __po_hi_marshall_request_the_thread_control_heat_out (request, message, &(offset));

      break;
    }
    case the_thread_control_global_music_out:
    {
      __po_hi_marshall_request_the_thread_control_music_out (request, message, &(offset));

      break;
    }
    case the_thread_control_global_alarm_out:
    {
      __po_hi_marshall_request_the_thread_control_alarm_out (request, message, &(offset));

      break;
    }
    case the_thread_control_global_gate_in:
    {
      __po_hi_marshall_request_the_thread_control_gate_in (request, message, &(offset));

      break;
    }
    case the_thread_control_global_gate_out:
    {
      __po_hi_marshall_request_the_thread_control_gate_out (request, message, &(offset));

      break;
    }
    case the_thread_awake_global_motion_in:
    {
      __po_hi_marshall_request_the_thread_awake_motion_in (request, message, &(offset));

      break;
    }
    case the_thread_awake_global_motion_out:
    {
      __po_hi_marshall_request_the_thread_awake_motion_out (request, message, &(offset));

      break;
    }
    case the_thread_awake_rules_global_motion_in:
    {
      __po_hi_marshall_request_the_thread_awake_rules_motion_in (request, message, &(offset));

      break;
    }
    case the_thread_awake_rules_global_coffee_out:
    {
      __po_hi_marshall_request_the_thread_awake_rules_coffee_out (request, message, &(offset));

      break;
    }
    case the_thread_video_global_video_in:
    {
      __po_hi_marshall_request_the_thread_video_video_in (request, message, &(offset));

      break;
    }
    case the_thread_video_global_video_out:
    {
      __po_hi_marshall_request_the_thread_video_video_out (request, message, &(offset));

      break;
    }
    case the_thread_video_global_video_not_recognized:
    {
      __po_hi_marshall_request_the_thread_video_video_not_recognized (request, message, &(offset));

      break;
    }
    case the_thread_car_global_motion_in:
    {
      __po_hi_marshall_request_the_thread_car_motion_in (request, message, &(offset));

      break;
    }
    case the_thread_car_global_motion_out:
    {
      __po_hi_marshall_request_the_thread_car_motion_out (request, message, &(offset));

      break;
    }
    default:
    {
      break;
    }
  }
}

void __po_hi_unmarshall_request 
    (__po_hi_request_t* request,
    __po_hi_msg_t* message)
{
  __po_hi_uint32_t offset;

  offset = 0;
  __po_hi_unmarshall_port (&(request->port), message);
  switch (request->port)
  {
    case the_thread_motion_global_motion_in:
    {
      __po_hi_unmarshall_request_the_thread_motion_motion_in (request, message, &(offset));

      break;
    }
    case the_thread_motion_global_motion_out:
    {
      __po_hi_unmarshall_request_the_thread_motion_motion_out (request, message, &(offset));

      break;
    }
    case the_thread_control_global_video_not_recognized:
    {
      __po_hi_unmarshall_request_the_thread_control_video_not_recognized (request, message, &(offset));

      break;
    }
    case the_thread_control_global_motion_in:
    {
      __po_hi_unmarshall_request_the_thread_control_motion_in (request, message, &(offset));

      break;
    }
    case the_thread_control_global_camera_out:
    {
      __po_hi_unmarshall_request_the_thread_control_camera_out (request, message, &(offset));

      break;
    }
    case the_thread_control_global_light_out:
    {
      __po_hi_unmarshall_request_the_thread_control_light_out (request, message, &(offset));

      break;
    }
    case the_thread_control_global_heat_out:
    {
      __po_hi_unmarshall_request_the_thread_control_heat_out (request, message, &(offset));

      break;
    }
    case the_thread_control_global_music_out:
    {
      __po_hi_unmarshall_request_the_thread_control_music_out (request, message, &(offset));

      break;
    }
    case the_thread_control_global_alarm_out:
    {
      __po_hi_unmarshall_request_the_thread_control_alarm_out (request, message, &(offset));

      break;
    }
    case the_thread_control_global_gate_in:
    {
      __po_hi_unmarshall_request_the_thread_control_gate_in (request, message, &(offset));

      break;
    }
    case the_thread_control_global_gate_out:
    {
      __po_hi_unmarshall_request_the_thread_control_gate_out (request, message, &(offset));

      break;
    }
    case the_thread_awake_global_motion_in:
    {
      __po_hi_unmarshall_request_the_thread_awake_motion_in (request, message, &(offset));

      break;
    }
    case the_thread_awake_global_motion_out:
    {
      __po_hi_unmarshall_request_the_thread_awake_motion_out (request, message, &(offset));

      break;
    }
    case the_thread_awake_rules_global_motion_in:
    {
      __po_hi_unmarshall_request_the_thread_awake_rules_motion_in (request, message, &(offset));

      break;
    }
    case the_thread_awake_rules_global_coffee_out:
    {
      __po_hi_unmarshall_request_the_thread_awake_rules_coffee_out (request, message, &(offset));

      break;
    }
    case the_thread_video_global_video_in:
    {
      __po_hi_unmarshall_request_the_thread_video_video_in (request, message, &(offset));

      break;
    }
    case the_thread_video_global_video_out:
    {
      __po_hi_unmarshall_request_the_thread_video_video_out (request, message, &(offset));

      break;
    }
    case the_thread_video_global_video_not_recognized:
    {
      __po_hi_unmarshall_request_the_thread_video_video_not_recognized (request, message, &(offset));

      break;
    }
    case the_thread_car_global_motion_in:
    {
      __po_hi_unmarshall_request_the_thread_car_motion_in (request, message, &(offset));

      break;
    }
    case the_thread_car_global_motion_out:
    {
      __po_hi_unmarshall_request_the_thread_car_motion_out (request, message, &(offset));

      break;
    }
    default:
    {
      break;
    }
  }
}


