--------------------------------------------------------
--  This file was automatically generated by Ocarina  --
--  Do NOT hand-modify this file, as your             --
--  changes will be lost when you re-run Ocarina      --
--------------------------------------------------------
pragma Style_Checks
 ("NM32766");


package PolyORB_HI_Generated.Types is

  type motion_State is
   new Standard.Integer;

  --  motion_state'Object_Size ~= 32 bits

  motion_State_Default_Value : constant motion_State :=
   0;

end PolyORB_HI_Generated.Types;
