--------------------------------------------------------
--  This file was automatically generated by Ocarina  --
--  Do NOT hand-modify this file, as your             --
--  changes will be lost when you re-run Ocarina      --
--------------------------------------------------------
pragma Style_Checks
 ("NM32766");

with PolyORB_HI_Generated.Activity;
with PolyORB_HI.Messages;
with PolyORB_HI_Generated.Types;

package PolyORB_HI_Generated.Marshallers is

  --  Marshallers for interface type of thread readmotion.impl

  procedure Marshall
   (Data : PolyORB_HI_Generated.Activity.syst_ReadMotion_impl_Interface;
    Message : in out PolyORB_HI.Messages.Message_Type);

  procedure Unmarshall
   (Port : PolyORB_HI_Generated.Activity.syst_ReadMotion_impl_Port_Type;
    Data : out PolyORB_HI_Generated.Activity.syst_ReadMotion_impl_Interface;
    Message : in out PolyORB_HI.Messages.Message_Type);

  --  Marshallers for DATA type state

  procedure Marshall
   (Data : PolyORB_HI_Generated.Types.State;
    Message : in out PolyORB_HI.Messages.Message_Type);

  procedure Unmarshall
   (Data : out PolyORB_HI_Generated.Types.State;
    Message : in out PolyORB_HI.Messages.Message_Type);

  --  Marshallers for interface type of thread controlrules.impl

  procedure Marshall
   (Data : PolyORB_HI_Generated.Activity.syst_ControlRules_impl_Interface;
    Message : in out PolyORB_HI.Messages.Message_Type);

  procedure Unmarshall
   (Port : PolyORB_HI_Generated.Activity.syst_ControlRules_impl_Port_Type;
    Data : out PolyORB_HI_Generated.Activity.syst_ControlRules_impl_Interface;
    Message : in out PolyORB_HI.Messages.Message_Type);

  --  Marshallers for interface type of thread awakemotion.impl

  procedure Marshall
   (Data : PolyORB_HI_Generated.Activity.syst_AwakeMotion_impl_Interface;
    Message : in out PolyORB_HI.Messages.Message_Type);

  procedure Unmarshall
   (Port : PolyORB_HI_Generated.Activity.syst_AwakeMotion_impl_Port_Type;
    Data : out PolyORB_HI_Generated.Activity.syst_AwakeMotion_impl_Interface;
    Message : in out PolyORB_HI.Messages.Message_Type);

  --  Marshallers for interface type of thread awakerules.impl

  procedure Marshall
   (Data : PolyORB_HI_Generated.Activity.syst_AwakeRules_impl_Interface;
    Message : in out PolyORB_HI.Messages.Message_Type);

  procedure Unmarshall
   (Port : PolyORB_HI_Generated.Activity.syst_AwakeRules_impl_Port_Type;
    Data : out PolyORB_HI_Generated.Activity.syst_AwakeRules_impl_Interface;
    Message : in out PolyORB_HI.Messages.Message_Type);

  --  Marshallers for interface type of thread processvideo.impl

  procedure Marshall
   (Data : PolyORB_HI_Generated.Activity.syst_ProcessVideo_impl_Interface;
    Message : in out PolyORB_HI.Messages.Message_Type);

  procedure Unmarshall
   (Port : PolyORB_HI_Generated.Activity.syst_ProcessVideo_impl_Port_Type;
    Data : out PolyORB_HI_Generated.Activity.syst_ProcessVideo_impl_Interface;
    Message : in out PolyORB_HI.Messages.Message_Type);

  --  Marshallers for interface type of thread carcheck.impl

  procedure Marshall
   (Data : PolyORB_HI_Generated.Activity.syst_CarCheck_impl_Interface;
    Message : in out PolyORB_HI.Messages.Message_Type);

  procedure Unmarshall
   (Port : PolyORB_HI_Generated.Activity.syst_CarCheck_impl_Port_Type;
    Data : out PolyORB_HI_Generated.Activity.syst_CarCheck_impl_Interface;
    Message : in out PolyORB_HI.Messages.Message_Type);

end PolyORB_HI_Generated.Marshallers;
