--------------------------------------------------------
--  This file was automatically generated by Ocarina  --
--  Do NOT hand-modify this file, as your             --
--  changes will be lost when you re-run Ocarina      --
--------------------------------------------------------
pragma Style_Checks
 ("NM32766");

with PolyORB_HI_Generated.Types;

package PolyORB_HI_Generated.Subprograms is

  procedure syst_Motion_Processing
   (movement_data : PolyORB_HI_Generated.Types.motion_State;
    person_in_room : out PolyORB_HI_Generated.Types.motion_State);

  procedure syst_Control_Processing
   (movement_data : PolyORB_HI_Generated.Types.motion_State;
    video_data : PolyORB_HI_Generated.Types.motion_State;
    camera_out : out PolyORB_HI_Generated.Types.motion_State;
    light_out : out PolyORB_HI_Generated.Types.motion_State;
    heat_out : out PolyORB_HI_Generated.Types.motion_State;
    music_out : out PolyORB_HI_Generated.Types.motion_State;
    alarm_out : out PolyORB_HI_Generated.Types.motion_State;
    gate_in : PolyORB_HI_Generated.Types.motion_State;
    gate_out : out PolyORB_HI_Generated.Types.motion_State);

  procedure syst_Awake_Processing
   (movement_data : PolyORB_HI_Generated.Types.motion_State;
    coffee_out : out PolyORB_HI_Generated.Types.motion_State);

  procedure syst_Video_Processing
   (video_in : PolyORB_HI_Generated.Types.motion_State;
    video_out : out PolyORB_HI_Generated.Types.motion_State;
    video_not_recognized : out PolyORB_HI_Generated.Types.motion_State);

private
  pragma Import
   (C,
    syst_Motion_Processing,
    "readMotion");

  pragma Import
   (C,
    syst_Control_Processing,
    "readMotion");

  pragma Import
   (C,
    syst_Awake_Processing,
    "readMotion");

  pragma Import
   (C,
    syst_Video_Processing,
    "readMotion");

end PolyORB_HI_Generated.Subprograms;
