--------------------------------------------------------
--  This file was automatically generated by Ocarina  --
--  Do NOT hand-modify this file, as your             --
--  changes will be lost when you re-run Ocarina      --
--------------------------------------------------------
pragma Style_Checks
 ("NM32766");


package PolyORB_HI_Generated.Deployment is

  pragma Preelaborate;

  --  For each node in the distributed application add an enumerator

  type Node_Type is
   (the_controller_K);

  --  Representation clause to have consistent positions for enumerators

  for Node_Type use
   (the_controller_K =>
     1);

  --  Size of Node_Type fixed to 8 bits

  for Node_Type'Size use 8;

  Max_Node_Image_Size : constant Standard.Integer :=
   16;

  --  Maximal Node_Image size for this node

  --  Node Image

  subtype UT_Deployment_The_Controller_Node_Type_Range is
   Node_Type range Node_Type'First .. Node_Type'Last;

  subtype UT_Deployment_The_Controller_1_Max_Node_Image_Size is
   Integer range 1 .. Max_Node_Image_Size;

  subtype UT_Deployment_The_Controller_Node_Image_Component is
   Standard.String
     (UT_Deployment_The_Controller_1_Max_Node_Image_Size);

  type UT_Deployment_The_Controller_Node_Image_Array is
   array (UT_Deployment_The_Controller_Node_Type_Range)
     of UT_Deployment_The_Controller_Node_Image_Component;

  Node_Image : constant UT_Deployment_The_Controller_Node_Image_Array :=
   UT_Deployment_The_Controller_Node_Image_Array'
     (the_controller_K =>
       "the_controller_K");

  My_Node : constant Node_Type :=
   the_controller_K;

  --  For each thread in the distributed application nodes, add an enumerator

  type Entity_Type is
   (the_controller_the_thread_motion_K,
    the_controller_the_thread_control_K,
    the_controller_the_thread_awake_K,
    the_controller_the_thread_awake_rules_K,
    the_controller_the_thread_video_K,
    the_controller_the_thread_car_K);

  --  Representation clause to have consistent positions for enumerators

  for Entity_Type use
   (the_controller_the_thread_motion_K =>
     1,
    the_controller_the_thread_control_K =>
     2,
    the_controller_the_thread_awake_K =>
     3,
    the_controller_the_thread_awake_rules_K =>
     4,
    the_controller_the_thread_video_K =>
     5,
    the_controller_the_thread_car_K =>
     6);

  --  Size of Entity_Type fixed to 8 bits

  for Entity_Type'Size use 8;

  --  Entity Table

  subtype UT_Deployment_The_Controller_Entity_Type_Range is
   Entity_Type range Entity_Type'First .. Entity_Type'Last;

  type UT_Deployment_The_Controller_Entity_Table_Array is
   array (UT_Deployment_The_Controller_Entity_Type_Range)
     of Node_Type;

  Entity_Table : constant UT_Deployment_The_Controller_Entity_Table_Array :=
   UT_Deployment_The_Controller_Entity_Table_Array'
     (the_controller_the_thread_motion_K =>
       the_controller_K,
      the_controller_the_thread_control_K =>
       the_controller_K,
      the_controller_the_thread_awake_K =>
       the_controller_K,
      the_controller_the_thread_awake_rules_K =>
       the_controller_K,
      the_controller_the_thread_video_K =>
       the_controller_K,
      the_controller_the_thread_car_K =>
       the_controller_K);

  Max_Entity_Image_Size : constant Standard.Integer :=
   39;

  --  Maximal Entity_Image size for this node

  --  Entity Image

  subtype UT_Deployment_The_Controller_1_Max_Entity_Image_Size is
   Integer range 1 .. Max_Entity_Image_Size;

  subtype UT_Deployment_The_Controller_Entity_Image_Component is
   Standard.String
     (UT_Deployment_The_Controller_1_Max_Entity_Image_Size);

  type UT_Deployment_The_Controller_Entity_Image_Array is
   array (UT_Deployment_The_Controller_Entity_Type_Range)
     of UT_Deployment_The_Controller_Entity_Image_Component;

  Entity_Image : constant UT_Deployment_The_Controller_Entity_Image_Array :=
   UT_Deployment_The_Controller_Entity_Image_Array'
     (the_controller_the_thread_motion_K =>
       "the_controller_the_thread_motion_K     ",
      the_controller_the_thread_control_K =>
       "the_controller_the_thread_control_K    ",
      the_controller_the_thread_awake_K =>
       "the_controller_the_thread_awake_K      ",
      the_controller_the_thread_awake_rules_K =>
       "the_controller_the_thread_awake_rules_K",
      the_controller_the_thread_video_K =>
       "the_controller_the_thread_video_K      ",
      the_controller_the_thread_car_K =>
       "the_controller_the_thread_car_K        ");

  --  For each thread port in the distributed application nodes, add an 
  --  enumerator

  type Port_Type is
   (the_controller_the_thread_motion_motion_in_K,
    the_controller_the_thread_motion_motion_out_K,
    the_controller_the_thread_control_video_not_recognized_K,
    the_controller_the_thread_control_motion_in_K,
    the_controller_the_thread_control_gate_in_K,
    the_controller_the_thread_control_out_data_K,
    the_controller_the_thread_control_camera_out_K,
    the_controller_the_thread_awake_motion_in_K,
    the_controller_the_thread_awake_motion_out_K,
    the_controller_the_thread_awake_rules_motion_in_K,
    the_controller_the_thread_awake_rules_coffee_out_K,
    the_controller_the_thread_video_video_in_K,
    the_controller_the_thread_video_video_data_out_K,
    the_controller_the_thread_car_motion_in_K,
    the_controller_the_thread_car_motion_out_K);

  --  Representation clause to have consistent positions for enumerators

  for Port_Type use
   (the_controller_the_thread_motion_motion_in_K =>
     1,
    the_controller_the_thread_motion_motion_out_K =>
     2,
    the_controller_the_thread_control_video_not_recognized_K =>
     3,
    the_controller_the_thread_control_motion_in_K =>
     4,
    the_controller_the_thread_control_gate_in_K =>
     5,
    the_controller_the_thread_control_out_data_K =>
     6,
    the_controller_the_thread_control_camera_out_K =>
     7,
    the_controller_the_thread_awake_motion_in_K =>
     8,
    the_controller_the_thread_awake_motion_out_K =>
     9,
    the_controller_the_thread_awake_rules_motion_in_K =>
     10,
    the_controller_the_thread_awake_rules_coffee_out_K =>
     11,
    the_controller_the_thread_video_video_in_K =>
     12,
    the_controller_the_thread_video_video_data_out_K =>
     13,
    the_controller_the_thread_car_motion_in_K =>
     14,
    the_controller_the_thread_car_motion_out_K =>
     15);

  --  Size of Port_Type fixed to 16 bits

  for Port_Type'Size use 16;

  --  Port Table

  subtype UT_Deployment_The_Controller_Port_Type_Range is
   Port_Type range Port_Type'First .. Port_Type'Last;

  type UT_Deployment_The_Controller_Port_Table_Array is
   array (UT_Deployment_The_Controller_Port_Type_Range)
     of Entity_Type;

  Port_Table : constant UT_Deployment_The_Controller_Port_Table_Array :=
   UT_Deployment_The_Controller_Port_Table_Array'
     (the_controller_the_thread_motion_motion_in_K =>
       the_controller_the_thread_motion_K,
      the_controller_the_thread_motion_motion_out_K =>
       the_controller_the_thread_motion_K,
      the_controller_the_thread_control_video_not_recognized_K =>
       the_controller_the_thread_control_K,
      the_controller_the_thread_control_motion_in_K =>
       the_controller_the_thread_control_K,
      the_controller_the_thread_control_gate_in_K =>
       the_controller_the_thread_control_K,
      the_controller_the_thread_control_out_data_K =>
       the_controller_the_thread_control_K,
      the_controller_the_thread_control_camera_out_K =>
       the_controller_the_thread_control_K,
      the_controller_the_thread_awake_motion_in_K =>
       the_controller_the_thread_awake_K,
      the_controller_the_thread_awake_motion_out_K =>
       the_controller_the_thread_awake_K,
      the_controller_the_thread_awake_rules_motion_in_K =>
       the_controller_the_thread_awake_rules_K,
      the_controller_the_thread_awake_rules_coffee_out_K =>
       the_controller_the_thread_awake_rules_K,
      the_controller_the_thread_video_video_in_K =>
       the_controller_the_thread_video_K,
      the_controller_the_thread_video_video_data_out_K =>
       the_controller_the_thread_video_K,
      the_controller_the_thread_car_motion_in_K =>
       the_controller_the_thread_car_K,
      the_controller_the_thread_car_motion_out_K =>
       the_controller_the_thread_car_K);

  Max_Port_Image_Size : constant Standard.Integer :=
   56;

  --  Maximal Port_Image size for this node

  subtype Port_Sized_String is
   Standard.String
     (1 .. PolyORB_HI_Generated.Deployment.Max_Port_Image_Size);

  --  Port Image

  type UT_Deployment_The_Controller_Port_Image_Array is
   array (UT_Deployment_The_Controller_Port_Type_Range)
     of Port_Sized_String;

  Port_Image : constant UT_Deployment_The_Controller_Port_Image_Array :=
   UT_Deployment_The_Controller_Port_Image_Array'
     (the_controller_the_thread_motion_motion_in_K =>
       "the_controller_the_thread_motion_motion_in_K            ",
      the_controller_the_thread_motion_motion_out_K =>
       "the_controller_the_thread_motion_motion_out_K           ",
      the_controller_the_thread_control_video_not_recognized_K =>
       "the_controller_the_thread_control_video_not_recognized_K",
      the_controller_the_thread_control_motion_in_K =>
       "the_controller_the_thread_control_motion_in_K           ",
      the_controller_the_thread_control_gate_in_K =>
       "the_controller_the_thread_control_gate_in_K             ",
      the_controller_the_thread_control_out_data_K =>
       "the_controller_the_thread_control_out_data_K            ",
      the_controller_the_thread_control_camera_out_K =>
       "the_controller_the_thread_control_camera_out_K          ",
      the_controller_the_thread_awake_motion_in_K =>
       "the_controller_the_thread_awake_motion_in_K             ",
      the_controller_the_thread_awake_motion_out_K =>
       "the_controller_the_thread_awake_motion_out_K            ",
      the_controller_the_thread_awake_rules_motion_in_K =>
       "the_controller_the_thread_awake_rules_motion_in_K       ",
      the_controller_the_thread_awake_rules_coffee_out_K =>
       "the_controller_the_thread_awake_rules_coffee_out_K      ",
      the_controller_the_thread_video_video_in_K =>
       "the_controller_the_thread_video_video_in_K              ",
      the_controller_the_thread_video_video_data_out_K =>
       "the_controller_the_thread_video_video_data_out_K        ",
      the_controller_the_thread_car_motion_in_K =>
       "the_controller_the_thread_car_motion_in_K               ",
      the_controller_the_thread_car_motion_out_K =>
       "the_controller_the_thread_car_motion_out_K              ");

  --  Maximal message payload size for this node (in bits)

  Max_Payload_Size : constant Standard.Integer :=
   112;

  --  Biggest type: state

end PolyORB_HI_Generated.Deployment;
