--------------------------------------------------------
--  This file was automatically generated by Ocarina  --
--  Do NOT hand-modify this file, as your             --
--  changes will be lost when you re-run Ocarina      --
--------------------------------------------------------
pragma Style_Checks
 ("NM32766");

with Home;

package body PolyORB_HI_Generated.Subprograms is

  procedure syst_Motion_Processing
   (movement_data : PolyORB_HI_Generated.Types.State;
    person_in_room : out PolyORB_HI_Generated.Types.State)
   renames Home.ReadMotion;

  procedure syst_Control_Processing
   (movement_data : PolyORB_HI_Generated.Types.State;
    video_not_recognized : PolyORB_HI_Generated.Types.State;
    gate_in : PolyORB_HI_Generated.Types.State;
    out_data : out PolyORB_HI_Generated.Types.State)
   renames Home.ControlRules;

  procedure syst_Awake_Processing
   (movement_data : PolyORB_HI_Generated.Types.State;
    motion_out : out PolyORB_HI_Generated.Types.State)
   renames Home.AwakeMotion;

  procedure syst_Awake_Processing_Rules
   (movement_data : PolyORB_HI_Generated.Types.State;
    coffee_out : out PolyORB_HI_Generated.Types.State)
   renames Home.Awake_Processing_Rules;

  procedure syst_Video_Processing
   (video_in : PolyORB_HI_Generated.Types.State;
    video_data_out : out PolyORB_HI_Generated.Types.State)
   renames Home.ProcessVideo;

  procedure syst_Car_Processing
   (movement_data : PolyORB_HI_Generated.Types.State;
    car_detected : out PolyORB_HI_Generated.Types.State)
   renames Home.CarCheck;

end PolyORB_HI_Generated.Subprograms;
