#include <deployment.h>
#include <po_hi_types.h>
/*****************************************************/
/*  This file was automatically generated by Ocarina */
/*  Do NOT hand-modify this file, as your            */
/*  changes will be lost when you re-run Ocarina     */
/*****************************************************/
const char* __po_hi_ports_names[__PO_HI_NB_PORTS] = {"the_thread_motion_global_motion_in","the_thread_motion_global_motion_out","the_thread_control_global_video_not_recognized","the_thread_control_global_motion_in","the_thread_control_global_camera_out","the_thread_control_global_light_out","the_thread_control_global_heat_out","the_thread_control_global_music_out","the_thread_control_global_alarm_out","the_thread_control_global_gate_in","the_thread_control_global_gate_out","the_thread_awake_global_motion_in","the_thread_awake_global_motion_out","the_thread_awake_rules_global_motion_in","the_thread_awake_rules_global_coffee_out","the_thread_video_global_video_in","the_thread_video_global_video_out","the_thread_video_global_video_not_recognized","the_thread_car_global_motion_in","the_thread_car_global_motion_out"};

