#ifndef __OCARINA_GENERATED_SUBPROGRAMS_H_
#define __OCARINA_GENERATED_SUBPROGRAMS_H_ 
#include <types.h>
/*****************************************************/

/*  This file was automatically generated by Ocarina */

/*  Do NOT hand-modify this file, as your            */

/*  changes will be lost when you re-run Ocarina     */

/*****************************************************/

void syst__motion_processing 
    (home_types__motion_state movement_data,
    home_types__motion_state* person_in_room);

void syst__control_processing 
    (home_types__motion_state movement_data,
    home_types__motion_state video_data,
    home_types__motion_state* camera_out,
    home_types__motion_state* light_out,
    home_types__motion_state* heat_out,
    home_types__motion_state* music_out,
    home_types__motion_state* alarm_out,
    home_types__motion_state gate_in,
    home_types__motion_state* gate_out);

void syst__awake_processing 
    (home_types__motion_state movement_data,
    home_types__motion_state* motion_out);

void syst__awake_processing_rules 
    (home_types__motion_state movement_data,
    home_types__motion_state* coffee_out);

void syst__video_processing 
    (home_types__motion_state video_in,
    home_types__motion_state* video_out,
    home_types__motion_state* video_not_recognized);

void syst__car_processing 
    (home_types__motion_state movement_data,
    home_types__motion_state* car_detected);

#endif
