#include "subprograms.h"
#include <types.h>
/*****************************************************/
/*  This file was automatically generated by Ocarina */
/*  Do NOT hand-modify this file, as your            */
/*  changes will be lost when you re-run Ocarina     */
/*****************************************************/
void readmotion 
    (home_types__motion_state movement_data,
    home_types__motion_state* person_in_room);
void syst__motion_processing 
    (home_types__motion_state movement_data,
    home_types__motion_state* person_in_room)
{

  readmotion (movement_data, person_in_room);
}

void readmotion 
    (home_types__motion_state movement_data,
    home_types__motion_state video_data,
    home_types__motion_state* camera_out,
    home_types__motion_state* light_out,
    home_types__motion_state* heat_out,
    home_types__motion_state* music_out,
    home_types__motion_state* alarm_out,
    home_types__motion_state gate_in,
    home_types__motion_state* gate_out);
void syst__control_processing 
    (home_types__motion_state movement_data,
    home_types__motion_state video_data,
    home_types__motion_state* camera_out,
    home_types__motion_state* light_out,
    home_types__motion_state* heat_out,
    home_types__motion_state* music_out,
    home_types__motion_state* alarm_out,
    home_types__motion_state gate_in,
    home_types__motion_state* gate_out)
{

  readmotion (movement_data, video_data, camera_out, light_out, heat_out, music_out, alarm_out, gate_in, gate_out);
}

void readmotion 
    (home_types__motion_state movement_data,
    home_types__motion_state* motion_out);
void syst__awake_processing 
    (home_types__motion_state movement_data,
    home_types__motion_state* motion_out)
{

  readmotion (movement_data, motion_out);
}

void readmotion 
    (home_types__motion_state movement_data,
    home_types__motion_state* coffee_out);
void syst__awake_processing_rules 
    (home_types__motion_state movement_data,
    home_types__motion_state* coffee_out)
{

  readmotion (movement_data, coffee_out);
}

void readmotion 
    (home_types__motion_state video_in,
    home_types__motion_state* video_out,
    home_types__motion_state* video_not_recognized);
void syst__video_processing 
    (home_types__motion_state video_in,
    home_types__motion_state* video_out,
    home_types__motion_state* video_not_recognized)
{

  readmotion (video_in, video_out, video_not_recognized);
}

void readmotion 
    (home_types__motion_state movement_data,
    home_types__motion_state* car_detected);
void syst__car_processing 
    (home_types__motion_state movement_data,
    home_types__motion_state* car_detected)
{

  readmotion (movement_data, car_detected);
}


