#include "subprograms.h"
#include <types.h>
/*****************************************************/
/*  This file was automatically generated by Ocarina */
/*  Do NOT hand-modify this file, as your            */
/*  changes will be lost when you re-run Ocarina     */
/*****************************************************/
void readmotion 
    (home_types__state movement_data,
    home_types__state* person_in_room);
void syst__motion_processing 
    (home_types__state movement_data,
    home_types__state* person_in_room)
{

  readmotion (movement_data, person_in_room);
}

void controlrules 
    (home_types__state movement_data,
    home_types__state video_not_recognized,
    home_types__state* camera_out,
    home_types__state* light_out,
    home_types__state* heat_out,
    home_types__state* music_out,
    home_types__state* alarm_out,
    home_types__state gate_in,
    home_types__state* gate_out);
void syst__control_processing 
    (home_types__state movement_data,
    home_types__state video_not_recognized,
    home_types__state* camera_out,
    home_types__state* light_out,
    home_types__state* heat_out,
    home_types__state* music_out,
    home_types__state* alarm_out,
    home_types__state gate_in,
    home_types__state* gate_out)
{

  controlrules (movement_data, video_not_recognized, camera_out, light_out, heat_out, music_out, alarm_out, gate_in, gate_out);
}

void awakemotion 
    (home_types__state movement_data,
    home_types__state* motion_out);
void syst__awake_processing 
    (home_types__state movement_data,
    home_types__state* motion_out)
{

  awakemotion (movement_data, motion_out);
}

void awake_proccessing_rules 
    (home_types__state movement_data,
    home_types__state* coffee_out);
void syst__awake_processing_rules 
    (home_types__state movement_data,
    home_types__state* coffee_out)
{

  awake_proccessing_rules (movement_data, coffee_out);
}

void processvideo 
    (home_types__state video_in,
    home_types__state* video_out,
    home_types__state* video_not_recognized);
void syst__video_processing 
    (home_types__state video_in,
    home_types__state* video_out,
    home_types__state* video_not_recognized)
{

  processvideo (video_in, video_out, video_not_recognized);
}

void carcheck 
    (home_types__state movement_data,
    home_types__state* car_detected);
void syst__car_processing 
    (home_types__state movement_data,
    home_types__state* car_detected)
{

  carcheck (movement_data, car_detected);
}


